version: '3.9'
services:
  mongo:
    image: mongo:6
    container_name: shodh-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: shodh-backend
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/shodh
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: shodh-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
